### ISSUE TITLE
使用最新的MDK-SDK无法编译

### ISSUE THREAD

**Issue by wangwenx190** [wang-bin/qtmultimedia-plugins-mdk#1]
https://github.com/wang-bin/qtmultimedia-plugins-mdk/blob/4939563c82d976a17e0dd454b3c140873430ad46/src/mediaservice/iodevice.h#L3
编译器提示找不到“mdk/MediaIO.h”，最新的MDK-SDK确实也没有这个文件。难道以前的版本有，后来删掉了，这边忘了更新代码？
https://github.com/wang-bin/qtmultimedia-plugins-mdk/blob/4939563c82d976a17e0dd454b3c140873430ad46/src/mediaservice/mediaservice.pro#L44
这个不是Qt Multimedia的插件吗？安装路径应该是`$$[QT_INSTALL_PLUGINS]/mediaservice`吧？而且没必要限定在Unix系统，Windows系统也支持install。
https://github.com/wang-bin/qtmultimedia-plugins-mdk/blob/4939563c82d976a17e0dd454b3c140873430ad46/src/mediaservice/mediaservice.pro#L49
Windows平台上没有`/usr/local/include`这个路径，这里不应该判断一下，根据不同的平台添加不同的路径吗？而且Unix系统默认会包含那个路径的吧，不用手动写进去。
https://github.com/wang-bin/qtmultimedia-plugins-mdk/blob/4939563c82d976a17e0dd454b3c140873430ad46/src/mediaservice/mediaservice.pro#L71
没有找到叫“mdk_mediaservice.json”的文件，倒是有一个“plugin.json”，文件改过名？
https://github.com/wang-bin/qtmultimedia-plugins-mdk/blob/4939563c82d976a17e0dd454b3c140873430ad46/src/mediaservice/mediaservice.pro#L74
https://github.com/wang-bin/qtmultimedia-plugins-mdk/blob/4939563c82d976a17e0dd454b3c140873430ad46/src/mediaservice/mediaservice.pro#L75
没必要这样写，使用`CONFIG += rtti_off`这一句就可以实现禁用RTTI的效果，qmake会根据不同的编译器为编译器和连接器添加不同的参数。而且MSVC也不支持这个参数，MSVC要使用`/GR-`来禁用RTTI。

**Comment by wangwenx190** [comment]
https://github.com/wang-bin/qtmultimedia-plugins-mdk/blob/4939563c82d976a17e0dd454b3c140873430ad46/src/mediaservice/mediaservice.pro#L67
https://github.com/wang-bin/qtmultimedia-plugins-mdk/blob/4939563c82d976a17e0dd454b3c140873430ad46/src/mediaservice/mediaservice.pro#L68
https://github.com/wang-bin/qtmultimedia-plugins-mdk/blob/4939563c82d976a17e0dd454b3c140873430ad46/src/mediaservice/mediaservice.pro#L69
我看Qt文档里说不推荐外部工程这样写，这是Qt内部插件的写法。外部插件的写法是`TEMPLATE = lib`和`CONFIG += plugin`

**Comment by wang-bin** [comment]
这个pro复制qtmultimedia里插件的稍微改改

**Comment by wangwenx190** [comment]
pro文件的问题是小事，我自己都能改，但缺少头文件没法编译啊，直接卡住了。

**Comment by wang-bin** [comment]
有些头文件还没有abi无关的版本。mdk里的接口分为个三层次，目前提供的c层和c++abi 无关的cpp层，这两个都是同一个二进制sdk可以给任意编译器使用。可以给你一份abi层的头文件，后面封装好了就都公开

**Comment by wangwenx190** [comment]
行，多谢。麻烦您了。
